# Generated by Django 5.1.3 on 2024-12-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analitics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("month_year", models.CharField(max_length=255, unique=True)),
                (
                    "total_spending",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "total_impact_from_employees",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                (
                    "total_impact_from_users",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Operation_OLAP",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Money_Used",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                ("Time_Completed", models.DateTimeField()),
                ("Operation_Type", models.CharField(max_length=255)),
                ("User_ID", models.IntegerField()),
                ("Time_Started", models.DateTimeField()),
            ],
        ),
    ]
