# Generated by Django 5.1.3 on 2024-12-05 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_analitics_operation_olap"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Analitics",
        ),
        migrations.DeleteModel(
            name="Operation_OLAP",
        ),
    ]
