# Generated by Django 5.1.3 on 2024-12-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_operation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operation",
            name="Time_started",
        ),
    ]
