# Generated by Django 5.1.3 on 2024-12-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_operation_time_started"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Year_Enrolled", models.IntegerField()),
                ("Position", models.CharField(max_length=255)),
                ("Office", models.CharField(max_length=255)),
            ],
        ),
    ]
