# Generated by Django 5.1.3 on 2024-12-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operation_olap",
            name="Time_started",
        ),
    ]
