# Generated by Django 5.1.3 on 2024-12-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_operation_olap_time_started"),
    ]

    operations = [
        migrations.CreateModel(
            name="Example",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("added_Field", models.CharField(max_length=255, null=True, blank=True)),
                ("address", models.CharField(max_length=255, null=True, blank=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="Example",
            constraint=models.UniqueConstraint(fields=["ID", "added_Field"], name="unique"),
        ),
        migrations.AddIndex(
            model_name="Example",
            index=models.Index(fields=["address"], name="address_idx"),
        ),
    ]
