# Generated by Django 5.1.3 on 2024-12-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_example"),
    ]

    operations = [
        migrations.CreateModel(
            name="Example1",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="example",
            name="unique",
        ),
        migrations.RemoveIndex(
            model_name="example",
            name="address_idx",
        ),
        migrations.RemoveField(
            model_name="example",
            name="added_Field",
        ),
        migrations.RemoveField(
            model_name="example",
            name="address",
        ),
    ]
